---
title: "HW3"
author: "enshapir"
date: "September 25, 2018"
output: html_document
---

```{r load libraries, include=FALSE}
library(tidyverse)
library(rjson)
library(sf)
library(maptools)
library(rgdal)
library(leaflet)
library(leaflet.extras)

```

```{r load data, include=FALSE}

#sandy strom track data: https://www.nhc.noaa.gov/gis/archive_besttrack_results.php?id=al18&year=2012&name=Hurricane%20SANDY
#sandy flood data: https://www.nhc.noaa.gov/gis/archive_psurge_results.php?id=al18&year=2012&name=Hurricane%20SANDY
#US cities with populations: https://gist.github.com/Miserlou/c5cd8364bf9b2420bb29


#file path names of the data used
sandy.track.fp <- file.path('.', 'al182012_lin.shp', fsep = .Platform$file.sep)
sandy.raidus.fp <- file.path('.', 'al182012_radii.shp', fsep = .Platform$file.sep)
us.cities.fp <- file.path('.', 'cities.json', fsep = .Platform$file.sep)


#read in data
# leaflet only supports SF file formats for this type of data. 
sandy.track <- st_read(sandy.track.fp)
sandy.radius <- st_read(sandy.raidus.fp)
#reading in a json file
us.cities.json <- fromJSON(file=us.cities.fp)


#reproject the data
sandy.track$geometry <- st_transform(sandy.track$geometry, crs = '+proj=longlat +datum=WGS84')
sandy.radius$geometry <- st_transform(sandy.radius$geometry, crs = '+proj=longlat +datum=WGS84')


#creating vectors too pull apart the Json file with
city = c()
growth_from_2000_to_2013 = c()
latitude = c()
longitude = c()
population = c()
rank = c()
state = c()

#pulling apart the json file into collumns
for (i in 1:length(us.cities.json)) {
  city[i] <- us.cities.json[[i]]$city
  growth_from_2000_to_2013[i] <- us.cities.json[[i]]$growth_from_2000_to_2013
  latitude[i] <- us.cities.json[[i]]$latitude
  longitude[i] <- us.cities.json[[i]]$longitude
  population[i] <- us.cities.json[[i]]$population
  rank[i] <- us.cities.json[[i]]$rank
  state[i] <- us.cities.json[[i]]$state
}

#creating a dataframe from the Json columns. 
us.cities <- data.frame(city, growth_from_2000_to_2013, latitude, longitude, population, rank, state)

```

```{r echo=FALSE}

#creating color pallette for map
stormpal <- colorFactor(c("#6eff33", "#f0ff33", "#ffe333", "#ffc433", "#ff6b33", "#f32222", "#c20404"), c("Low", "Tropical Depression", "Extratropical Cyclone", "Tropical Storm", "Hurricane1", "Hurricane2", "Hurricane3"))

#plot sandy track and color based on storm type
leaflet()%>% 
  addProviderTiles("Stamen.Toner", options = providerTileOptions(noWrap = TRUE)) %>% 
  addCircles(data = us.cities, lng = ~longitude, lat = ~latitude, weight = 1,
    radius = ~sqrt(as.numeric(as.factor(population)))*100, color = '#da0feb') %>% 
  addLegend(color = '#da0feb', labels = 'Major Population Center', opacity = 1) %>% 
  addPolylines(data = sandy.track, color = ~stormpal(STORMTYPE), group = "Storm Track") %>% 
  addLegend(colors = c("#c20404", "#f32222", "#ff6b33", "#ffc433", "#ffe333", "#f0ff33", "#6eff33"), labels = c("Hurricane3", "Hurricane2", "Hurricane1", "Tropical Storm", "Extratropical Cyclone", "Tropical Depression", "Low" ), opacity = 1) %>% 
  addPolygons(data = sandy.radius, group = "Storm Size") %>% 
  addLayersControl(
    overlayGroups = c("Storm Track",  "Storm Size"),
    options = layersControlOptions(collapsed = FALSE)) 

 

```


